language: c

os:
 - linux
 - osx

env:
 - TEST=normal NODE_VERSION=12
 - TEST=normal NODE_VERSION=14
 - TEST=integration NODE_VERSION=12
 - TEST=integration NODE_VERSION=14

before_install:
    - nvm install $NODE_VERSION
    - nvm use --delete-prefix $NODE_VERSION || echo
    - if [[ $(npm -v) != 6* ]]; then npm i -g npm@6; fi;
    - npm install
    - if [[ "$TRAVIS_OS_NAME" == "linux" && "$TEST" == "integration" ]]; then
            export DISPLAY=:99.0;
            sh -e /etc/init.d/xvfb start;
            sleep 5;
      fi
    - if [[ "$TEST" == "integration" ]]; then
            export PATH="$HOME/.meteor:$PATH";
            if hash meteor 2>/dev/null;
            then
                meteor --version;
            else
                curl https://install.meteor.com/?release=2.6 | /bin/sh;
            fi;
      fi


script:
    - if [[ "$TEST" == "normal" ]]; then
        npm test;
      fi
    - if [[ "$TEST" == "integration" ]]; then
            npm run prepare-integration-tests;
            npm run test-integration;
      fi

after_success:
  - if [[ "$TEST" == "normal" ]]; then
      npm run coverage;
      npm run report-coverage;
    fi

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.electron
    - $HOME/.npm
    - $HOME/.meteor
    - tests/.__tmp_int

notifications:
  email:
    on_success: never
    on_failure: change
