name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        meteor: [ '2.6', '1.10.2' ]
    name: Meteor ${{ matrix.meteor }} sample

    steps:
      - uses: actions/checkout@v1
      - name: Setup meteor
        uses: CanyLink/setup-meteor@v1
        with:
          meteor-release: ${{ matrix.meteor }}
      - run: meteor npm install
      - run: meteor npm test